travis:
  secure:
    BINSTAR_TOKEN: kxpX9U7s7PPsldwQb5A2e6HMldO25j9swtHmZtos8sd0EaRL9GHlbTMq2b4/fXbaDnJ3d7bEXA5FBrAqcR1Os26ZF5pbq5dn6Dxzjcix3Xvufq/Vj2DeypfyhmBWu61tXgfxO5xSpSq09qLy3/otp6LI67fhxH4mqfLUPG34Qb2PZmyLBpZ990/9u6D18SS+rZDBLJifelqFH7FY+hhemc6n1KzgwJo+UM1vMZs7gPeDqkrqHjQH+A7wIIIbWicHqLitui64J4+DgbLxTzBnriqfEaZVcu36FGwTirTDU0Km6yu11PZrqrhtILqSRcVzzPVYYKydYaUVO6cmH+EAseY0YQcSfRvtepKrqaslGbOeQLmSW8vVR9veLpfmUClE3HuNxZebfKVqkUnkF5b+teYltkn42dwBxAiMuxyZ/lCKa7B8XfON06FLoxYAB2mtDVuhMLA1F/iGk7OYOR0w7b4xjbyHsIToIPfKIn//nY5Xzrcw8b+Clezx6ARnVXsvlS/a8c/pfC2hoiaG4khkruRKkz8hIA5dM+7sZT/za64Ovyufp/85BmMFIcT5r0wVpbXS03qLphMQiYZw+PQjSr9eDyjQYFLQ5j5zEZjR+oV5f9FPbbsxkKtrWsoHywSIirN5DsILpmi5o5I2jcEcXhrd/7UtSZ5In+djb7bF+Bc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
